Repository Rahul-Prasad-07/Ethereum-Fundamentals, pull requests merged in 2022-10, with the labels that each got.

#1 Introduction to Ethereum
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2022

#2 Adding : Architecture overview
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest2022

#4 Documentation : Ethereum Accounts
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest2022

#5 Changes : Add some imp points
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest2022

#7 ADD : Transactions in Ethereum in README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest2022

#8 Add new section : Block Anatomy
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest2022
